#!/bin/bash

BUILD_DIR=build
INSTALL_ROOT=${1}

mkdir -p ${BUILD_DIR}
cd ${BUILD_DIR}

mkdir -p ${INSTALL_ROOT}

CC=cc
CXX=CC

cmake -DNEKTAR_USE_MPI=ON\
      -DNEKTAR_USE_HDF5=ON\
      -DNEKTAR_USE_FFTW=ON \
      -DTHIRDPARTY_BUILD_BOOST=ON\
      -DTHIRDPARTY_BUILD_HDF5=ON\
      -DTHIRDPARTY_BUILD_FFTW=ON \
      -DNEKTAR_BUILD_UNIT_TESTS=OFF\
      -DCMAKE_INSTALL_PREFIX=${INSTALL_ROOT} ..
